version: "3.9"

services:
  api:
    build: .
    container_name: gerenciador_de_ofertas
    ports:
      - "8000:8000"
    env_file:
      - .env   # ✅ carrega automaticamente as variáveis do arquivo .env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload